@host = https://equifax-gnaranja-22.herokuapp.com/

GET {{host}}/api/productos/ HTTP/1.1
Accept: application/json

POST {{host}}/api/productos/ HTTP/1.1
Content-Type:application/json

{
    "descripcion":"producto1",
    "precio":10.5,
    "dueDate":"2012-04-23T18:25:43.511Z",
    "imageFileName":"baili.jpg",
    "status":"A"
}

GET {{host}}/api/productos/ HTTP/1.1 
Accept: application/json

GET {{host}}/api/productos/11 HTTP/1.1 
Accept: application/json

DELETE {{host}}/api/productos/7 HTTP/1.1 
Accept: application/json

PUT {{host}}/api/productos/ HTTP/1.1 
Content-Type: application/json

{
    "id":12,
    "descripcion": "Tequila Cuervo New"
}